services:
  yt_postgres:
    image: postgres:15
    container_name: yt_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - youtube_pgdata:/var/lib/postgresql/data

  airflow_postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASS}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data


  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow_web
    depends_on:
      - airflow_postgres
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@airflow_postgres:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__LOGGING__REMOTE_LOGGING: 'False'
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/scripts
    ports:
      - 8080:8080
    command: webserver


  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow_sched
    depends_on:
      - airflow-webserver
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__LOGGING__REMOTE_LOGGING: 'False'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@airflow_postgres:5432/${AIRFLOW_DB_NAME}
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/scripts
    command: scheduler

volumes:
  youtube_pgdata:
  airflow_pgdata:
